#include "prefix/prefix.h"

#include "data-mov/mov.h"
#include "data-mov/xchg.h"
#include "data-mov/movsx.h"
#include "data-mov/movzx.h"

#include "arith/dec.h"
#include "arith/inc.h"
#include "arith/neg.h"
#include "arith/imul.h"
#include "arith/mul.h"
#include "arith/idiv.h"
#include "arith/div.h"

#include "logic/and.h"
#include "logic/or.h"
#include "logic/not.h"
#include "logic/xor.h"
#include "logic/sar.h"
#include "logic/shl.h"
#include "logic/shr.h"
#include "logic/shrd.h"
#include "logic/sub.h"
#include "logic/call.h"
#include "logic/test.h"
#include "logic/push.h"
#include "logic/je.h"
#include "logic/cmp.h"
#include "logic/jmp.h"
#include "logic/jbe.h"
#include "logic/add.h"

#include "string/rep.h"

#include "misc/misc.h"

#include "special/special.h"
